# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for Roo Code Memory Bank MCP Server
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Copy source files
COPY src ./src

# Install dependencies and build
RUN npm ci \
    && npm run build

# Default command to start the MCP server over stdio
CMD ["node", "dist/index.js"]
